# Site settings
title: Brooke Sargent
email: brookesargent01@gmail.com	
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brookesargent.github.io" # the base hostname & protocol for your site
twitter_username: codegirlbrooke
github_username: brookesargent

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]