# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Brooke Sargent"
description: 
email: brookesargent01@gmail.com  
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Brooke Sargent'
author: 'Brooke Sargent'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http//brookesargent.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@codegirlbrooke'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/codegirlbrooke
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="


  - icon:	github
    url:	https://github.com/brookesargent
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

