# Site settings
title: Brooke Sargent
email: brookesargent01@gmail.com
description: Here you can follow my code journey. I'll be making regular updates about what I'm learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brookesargent.github.io" # the base hostname & protocol for your site
twitter_username: codegirlbrooke
github_username:  brookesargent01

# Build settings
markdown: kramdown
